const THEME_MAP_ID = [
  'Close',
  'Biometry',
  'Qr',
  'Search',
  'Folder',
  'Wallet',
  'Graph',
  'Bookmark',
  'Browser',
  'Category',
  'Home',
  'Notification',
  'Chat',
  'Heart',
  'Paper',
  'Plus',
  'Minus',
  'PaperPlus',
  'PaperNegative',
  'PaperFail',
  'PaperDownload',
  'PaperUpload',
  'Send',
  'Password',
  'Swap',
  'Work',
  'Arrow1',
  'Arrow2',
  'Arrow3',
  'Arrow4',
  'ArrowMini1',
  'ArrowMini2',
  'Scan',
  'Activity',
  'Calendar',
  'Message',
  'PlusMini',
  'ChartMini',
  'Game',
  'Bag1',
  'Bag2',
  'TicketStar',
  'MoreCircle',
  'MoreSquare',
  'Discount',
  'Buy',
  'Web',
  'InfoMini',
  'DangerMini',
  'CloseMini',
  'TickMini',
  'Video',
  'Discovery',
  'Location',
  'Document',
  'Setting',
  'Time',
  'VolumeUp',
  'VolumeDown',
  'VolumeOff',
  'Star',
  'Select',
  'Ticket',
  'Camera',
  'Profile',
  'AddUser',
  'TwoUser',
  'ThreeUser',
  'Login',
  'Logout',
  'Download',
  'Upload',
  'Voice1',
  'Voice2',
  'Delete',
  'Edit',
  'PlayMini',
  'ShieldDone',
  'ShieldFail',
  'Show',
  'Hide',
  'Filter1',
  'Filter2',
  'Image',
  'Call',
  'Calling',
  'CallMissed',
  'CallSilent',
  'Lock',
  'Unlock',
  'Resources',
  'Language',
] as const;
const THEME_MAP_CHECKBOX = [
  'Radio-true',
  'Radio-false',
  'Square-true',
  'Square-false',
  'Heart-true',
  'Heart-false',
  'Arrow',
] as const;
const THEME_MAP_LOADING = ['Line', 'Circle', 'Blocks', 'Balls'] as const;
const THEME_MAP_LOGO = ['Jenesei', 'BustMarket'] as const;

export const THEME_MAP = {
  id: THEME_MAP_ID,
  checkbox: THEME_MAP_CHECKBOX,
  loading: THEME_MAP_LOADING,
  logo: THEME_MAP_LOGO,
};
