name: deploy-node

on:
  workflow_dispatch:
    inputs:
      build_folder:
        description: "Build output folder"
        required: false
        default: "build"
        type: string
      env_property:
        description: "Environment property to set version in .env file, e.g., VITE_APP_VERSION"
        default: "VITE_APP_VERSION"
        required: false
        type: string
      version_type:
        description: "Version bump"
        required: false
        default: "none"
        type: choice
        options:
          - none
      package_manager:
        description: "Package manager"
        required: false
        default: "yarn"
        type: choice
        options:
          - npm
          - yarn
          - bun
          - pnpm
      add_branch_name:
        description: 'Add branch name to version'
        required: false
        type: boolean
        default: true
      add_build_number:
        description: 'Add build number to version'
        required: false
        type: boolean
        default: true
jobs:
  call-publisher:
    uses: jenesei-software/.github/.github/workflows/deploy-node.yml@main
    with:
      env_property: ${{ inputs.env_property }}
      build_folder: ${{ inputs.build_folder }}
      version_type: ${{ inputs.version_type }}
      package_manager: ${{ inputs.package_manager }}
      add_branch_name: ${{ inputs.add_branch_name }}
      add_build_number: ${{ inputs.add_build_number }}
    secrets:
      ACCESS_GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN  }}